name: py27
channels:
  - damianavila82
  - defaults
dependencies:
  - python=2.7
  - rise
  - jupyter
  - tabulate
  - networkx
  - seaborn
  - pyyaml
  - cython
  - pip:
    - elephant
    - gitpython
    - neo
    - sciunit
    - rdflib

