name: networkunit_env
channels:
  - damianavila82
  - defaults
dependencies:
  - rise
  - jupyter
  - tabulate
  - networkx
  - seaborn
  - pyyaml
  - cython
  - numpy>=1.15.3
  - pip:
    - elephant
    - gitpython
    - networkunit
    - odml~=1.3.0
    - neo
    - sciunit
    - rdflib

