name: py36
channels:
  - damianavila82
  - defaults
dependencies:
  - rise
  - jupyter
  - tabulate
  - networkx
  - fastcluster
  - seaborn
  - pip:
    - elephant
    - gitpython
    - neo
    - sciunit


